swagger: "2.0"

info:
  version: 1.0.0
  title: User api
  description: this is user api
  
host: localhost:8000
basePath: /v1
schemes:
  - http
  - https
  
paths:
  /users:
    get:
      tags: [User]
      description: get users with pagination
      summary: get users with pagination
      produces:
        - application/json
      parameters:
        - in: query
          name: page
          type: number
          description: page number of list
          required: true
        - in: query
          name: limit
          type: number
          description: limit of list
          required: true
      responses:
        200:
          description: 'Success'
        500:
          description: 'Internal server error'
  /create:
    post:
      tags: [Create_user]
      description: create user accounts
      summary: create user profiles
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              id:
                type: number
                description: unique id of users
                example: 101
              name:
                type: string
                description: name of the user
                example: gowtham
              password:
                type: string
                description: password
                example: 123
            required:
              - id
              - name
              - password
      responses:
        200:
          description: 'Success'
        400:
          description: 'internal server error'
